source/fuel/urls.py
from django.urls import path
from .views import FuelListView, FuelCreateView, FuelUpdateView, FuelDeleteView
urlpatterns = [
    path('list/', FuelListView.as_view(), name='fuel_list'),
    # path('detail/<int:pk>', ServiceDetailView.as_view(), name='service_detail'),
    path('update/<int:pk>', FuelUpdateView.as_view(), name='fuel_update'),
    path('create/', FuelCreateView.as_view(), name='fuel_create'),
    path('delete/<int:pk>', FuelDeleteView.as_view(), name='fuel_delete'),

]

source/garage/urls.py
from django.urls import path
from .views import GarageListView, CarCreateView, CarUpdateView, CarDeleteView, CarMileageHistoryListView

urlpatterns = [
    path('car/list', GarageListView.as_view(), name='garage_list'),
    path('car/history/list', CarMileageHistoryListView.as_view(), name='car_history_list'),
    path('car/create', CarCreateView.as_view(), name='car_create'),
    path('car/<int:pk>/edit/', CarUpdateView.as_view(), name='car_edit'),
    path('car/<int:pk>/delete/', CarDeleteView.as_view(), name='car_delete'),
]

source/source/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from source.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home_page'),
    path('accounts/', include('accounts.urls')),
    path('garage/', include('garage.urls')),
    path('services/', include('services.urls')),
    path('notifications/', include('notifications.urls')),
    path('fuels/', include('fuel.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/garage/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType


class Car(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.PROTECT)
    title = models.CharField(max_length=200)
    date_of_purchase = models.DateField()
    state_number = models.CharField(max_length=50)
    car_mileage = models.IntegerField()
    car_photo = models.ImageField(upload_to='cars/', verbose_name='car_photo', null=True, blank=True)
    is_deleted = models.BooleanField(default=False)
    edited_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class CarMileageHistory(models.Model):
    car_mileage = models.IntegerField()
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    # Эти поля вместе представляют GenericForeignKey
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    parent_object = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return f'Car Mileage History for {self.parent_object}'

# Create your models here.

source/garage/forms.py
from django import forms
from .models import Car


class CarForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = ['title', 'date_of_purchase', 'state_number', 'car_mileage', 'car_photo']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'maxlength': '100'}),
            'date_of_purchase': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'state_number': forms.TextInput(attrs={'class': 'form-control', 'maxlength': '12'}),
            'car_mileage': forms.NumberInput(attrs={'class': 'form-control', 'min': '1', 'max': '1000000'}),
            'car_photo': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

source/garage/views.py
from django.db import transaction
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, UpdateView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from notifications.models import Notification
from notifications.tasks import check_notifications
from services.models import Service
from .models import Car, CarMileageHistory
from .forms import CarForm
from django.contrib.contenttypes.models import ContentType


class CarDeleteView(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = 'garage.delete_car'

    def get_object(self):
        car_id = self.kwargs.get('pk')
        return get_object_or_404(Car, id=car_id, user=self.request.user)

    def get(self, request, *args, **kwargs):
        car = self.get_object()
        self.delete_related_mileage_history(car)
        self.delete_related_services(car)
        self.delete_related_notifications(car)
        car.is_deleted = True
        car.save()
        return HttpResponseRedirect(self.get_success_url())

    # В этом обновленном коде я добавил метод delete_related_mileage_history,
    # который устанавливает is_deleted = True для всех записей CarMileageHistory,
    # связанных с удаляемым автомобилем. Я также обернул операции в методе delete_related_mileage_history в транзакцию,
    # чтобы гарантировать атомарное выполнение операций удаления.
    def delete_related_mileage_history(self, car):
        with transaction.atomic():
            mileage_history = CarMileageHistory.objects.filter(car=car)
            mileage_history.update(is_deleted=True)

    def delete_related_services(self, car):
        with transaction.atomic():
            services = Service.objects.filter(car=car, is_deleted=False)
            services.update(is_deleted=True)

    def delete_related_notifications(self, car):
        with transaction.atomic():
            notifications = Notification.objects.filter(car=car, is_deleted=False)
            notifications.update(turn_on=False)
            notifications.update(is_active=False)
            notifications.update(is_deleted=True)

    def get_success_url(self):
        return reverse_lazy('garage_list')


class CarUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Car
    form_class = CarForm
    template_name = 'garage/car_create_form.html'
    success_url = reverse_lazy('garage_list')
    permission_required = 'garage.change_car'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_editing'] = True
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        response = super().form_valid(form)

        # Создаем запись в CarMileageHistory после редактирования автомобиля
        CarMileageHistory.objects.create(
            car_mileage=form.cleaned_data['car_mileage'],
            car=form.instance,  # Указываем экземпляр автомобиля
            content_type=ContentType.objects.get_for_model(Car),
            object_id=form.instance.id
        )
        check_notifications()
        return response

    def get_queryset(self):
        #  что пользователь редактирует только свои автомобили
        qs = super().get_queryset()
        return qs.filter(user=self.request.user)


class GarageListView(LoginRequiredMixin, ListView):
    model = Car
    template_name = 'garage/car_list.html'
    context_object_name = 'cars'
    paginate_by = 6
    paginate_orphans = 0

    def get_queryset(self):
        check_notifications()
        # Получаем список автомобилей пользователя, учитывая, что они не удалены
        queryset = Car.objects.filter(user=self.request.user, is_deleted=False)

        # Для каждого автомобиля добавляем информацию о количестве непрочитанных уведомлений
        for car in queryset:
            car.unread_notifications_count = Notification.objects.filter(car=car, is_active=True).count()

        return queryset


class CarCreateView(LoginRequiredMixin, CreateView):
    model = Car
    form_class = CarForm
    template_name = 'garage/car_create_form.html'
    success_url = reverse_lazy('garage_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_editing'] = False
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        response = super().form_valid(form)

        # Создаем запись в CarMileageHistory после создания автомобиля
        CarMileageHistory.objects.create(
            car_mileage=form.cleaned_data['car_mileage'],
            car=form.instance,  # Указываем экземпляр автомобиля
            content_type=ContentType.objects.get_for_model(Car),
            object_id=form.instance.id
        )

        return response


class CarMileageHistoryListView(LoginRequiredMixin, ListView):
    model = CarMileageHistory
    template_name = 'garage/car_mileage_history_list.html'  # шаблон
    context_object_name = 'car_mileage_history'
    paginate_by = 6
    paginate_orphans = 0

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['car_id'] = self.request.GET.get('car_id')
        return context

    def get_queryset(self):
        car_id = self.request.GET.get('car_id')
        if car_id:
            return CarMileageHistory.objects.filter(car__user=self.request.user, car_id=car_id)
        else:
            return CarMileageHistory.objects.filter(car__user=self.request.user)

source/templates/garage/car_create_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <h2>{% if is_editing %}Edit{% else %}Create{% endif %} Car</h2>
  <form id="task-form" method="post" enctype="multipart/form-data" >
    {% csrf_token %}
      <div class="row">
          <div class="col-md-6">
              <div class="mb-3">
                {{ form.title.errors }}
                {{ form.title.label_tag }}
                {{ form.title }}
              </div>
              <div class="mb-3">
                  {{ form.date_of_purchase.errors }}
                {{ form.date_of_purchase.label_tag }}
                {{ form.date_of_purchase }}
              </div>
              <div class="mb-3">
                  {{ form.state_number.errors }}
                {{ form.state_number.label_tag }}
                {{ form.state_number }}
              </div>
              <div class="mb-3">
                  {{ form.car_mileage.errors }}
                {{ form.car_mileage.label_tag }}
                {{ form.car_mileage }}
              </div>
              <div class="mb-3" id="photo_file_card">
                  {{ form.car_photo.errors }}
                {{ form.car_photo.label_tag }}
                {{ form.car_photo }}
              </div>
          </div>
          <div class="col-md-6">
            <div class="col-md-4" id="service_photo_card" style="display: none">
                <div class="card mb-2" style="width: 18rem;">
                <img id="service_photo_file" src="{% static 'images/def_icon.png' %}" class="card-img-top" alt="...">
                    
                </div>
            </div>
              
          </div>
          
      </div>
    

    <button type="submit" class="btn btn-primary">{% if is_editing %}Edit{% else %}Create{% endif %}</button>
      <a href="{% url 'garage_list' %}" class="btn btn-danger">Cancel</a>
  </form>

{% endblock %}
{% block js %}
    <script>
$(document).ready(function() {
    // Получаем URL текущего изображения
    var currentImageUrl = $('#photo_file_card a').attr('href');
    if (currentImageUrl) {
        // Если URL существует
        // Отображаем карточку с изображением и устанавливаем URL изображения
        $('#service_photo_card').show();
        $('#service_photo_file').attr('src', currentImageUrl);
    }
});

$(document).ready(function() {
    // Функция для чтения и отображения выбранного изображения
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function(e) {
                $('#service_photo_file').attr('src', e.target.result);
                $('#service_photo_card').show();  // Показываем карточку с изображением
            }
            reader.readAsDataURL(input.files[0]);
        }
    }

    // Добавляем обработчик событий для поля загрузки файла
    $('#id_car_photo').change(function() {
        readURL(this);
    });
});
    </script>
    
{% endblock %}

source/templates/garage/car_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="row">
    <div class="container mb-3"><a href="{% url 'car_create' %}" class="btn btn-primary">Add car</a></div>
        {% include 'partials/pagination.html' %}
        {% for car in object_list %}
            <div class="col-md-4 d-flex justify-content-center">
                <div class="card mb-2" style="width: 18rem;">
                    {% if car.car_photo %}
                        <img src="{{ car.car_photo.url }}" class="card-img-top" alt="...">
                    {% else %}
                        <img src="{% static 'images/def_icon.png' %}" class="card-img-top" alt="...">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ car.title }}</h5>
                        <p class="card-text">Date of purchase - {{ car.date_of_purchase }}</p>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Number - {{ car.state_number }}</li>
                        <li class="list-group-item">Car mileage - {{ car.car_mileage }} km</li>
                        <li class="list-group-item">edited - {{ car.edited_at }}</li>
                    </ul>
                <div class="card-body">
                     <a href="{% url 'car_history_list' %}?car_id={{ car.id }}" class="btn btn-info">History</a>
                    <button type="button" class="btn btn-success position-relative">
                            <a style="text-decoration: none; color: white" href="{% url 'notifications_list' %}?car_id={{ car.id }}">Notifications</a>
                            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                             {{ car.unread_notifications_count }}
                            <span class="visually-hidden">notifications</span>
                            </span>
                        </button>

                </div>
                    <div class="card-body">
                        <a href="{% url 'car_edit' car.id %}" class="btn btn-primary">Edit</a>
                        <button type="button" class="btn btn-danger deleteButton" data-bs-toggle="modal"
                                data-bs-target="#deleteModal" data-car-id="{{ car.id }}">
                            Delete
                        </button>

                    </div>

                </div>
            </div>
        {% endfor %}
    </div>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Confirm deletion</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Are you sure you want to remove this car?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <a href="" class="btn btn-primary" id="confirmDelete">Delete</a>
                </div>
            </div>
        </div>
    </div>


    {% block js %}
        <!-- jQuery to handle the delete confirmation -->
        <script>
            $(document).ready(function () {
                $('.deleteButton').on('click', function () {
                    console.log("Delete button clicked");

                    var carId = $(this).data('car-id');
                    var url = "/garage/car/" + carId + "/delete/";
                    console.log("Delete URL: ", url);
                    $('#confirmDelete').attr('href', url);
                });
            });
        </script>
    {% endblock %}

{% endblock %}

source/templates/garage/car_mileage_history_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h2>Car Mileage History</h2>
{% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1&car_id={{ car_id }}">First</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}&car_id={{ car_id }}">Previous</a>
                </li>
            {% endif %}

            <li class="page-item active">
                <a class="page-link" href="?page={{ page_obj.number }}&car_id={{ car_id }}">{{ page_obj.number }}</a>
            </li>

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}&car_id={{ car_id }}">Next</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&car_id={{ car_id }}">Last</a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Car Mileage</th>
                <th scope="col">Created At</th>
                <th scope="col">Service</th>
                <th scope="col">Car</th>
                <th scope="col">is_deleted</th>
            </tr>
        </thead>
        <tbody>
            {% for history in car_mileage_history %}
            <tr>
                <td>{{ history.car_mileage }}</td>
                <td>{{ history.created_at }}</td>
                <td>{{ history.parent_object }}</td>
                <td>{{ history.car }}</td>
            <td>{% if history.is_deleted %}Yes{% else %}No{% endif %}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="3">No records found.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}