source/fuel/urls.py
from django.urls import path
from .views import FuelListView, FuelCreateView, FuelUpdateView, FuelDeleteView
urlpatterns = [
    path('list/', FuelListView.as_view(), name='fuel_list'),
    # path('detail/<int:pk>', ServiceDetailView.as_view(), name='service_detail'),
    path('update/<int:pk>', FuelUpdateView.as_view(), name='fuel_update'),
    path('create/', FuelCreateView.as_view(), name='fuel_create'),
    path('delete/<int:pk>', FuelDeleteView.as_view(), name='fuel_delete'),

]

source/services/urls.py
from django.urls import path
from .views import ServicesListView, ServiceDetailView, ServiceUpdateView, ServiceCreateView, ServiceDeleteView
urlpatterns = [
    path('list/', ServicesListView.as_view(), name='services_list'),
    path('detail/<int:pk>', ServiceDetailView.as_view(), name='service_detail'),
    path('update/<int:pk>', ServiceUpdateView.as_view(), name='service_update'),
    path('create/', ServiceCreateView.as_view(), name='service_create'),
    path('delete/<int:pk>', ServiceDeleteView.as_view(), name='service_delete'),

]

source/source/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from source.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home_page'),
    path('accounts/', include('accounts.urls')),
    path('garage/', include('garage.urls')),
    path('services/', include('services.urls')),
    path('notifications/', include('notifications.urls')),
    path('fuels/', include('fuel.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/services/models.py
from django.db import models
from garage.models import Car


class ServiceType(models.Model):
    title = models.CharField(max_length=100, unique=True)
    icon = models.ImageField(upload_to='services/icon/', verbose_name='services_icon', null=True, blank=True)

    def __str__(self):
        return self.title


class Service(models.Model):
    service_type = models.ForeignKey(ServiceType, on_delete=models.PROTECT, null=False, blank=False)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    car_mileage = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    edited_at = models.DateTimeField(auto_now=True)
    part_cost = models.DecimalField(max_digits=10, decimal_places=2)
    cost_of_work = models.DecimalField(max_digits=10, decimal_places=2)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    part_title = models.CharField(max_length=200)
    comment = models.TextField()
    photo = models.ImageField(upload_to='services/', verbose_name='services_photo', null=True, blank=True)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.title
# Create your models here.

source/services/forms.py
from django import forms

from garage.models import Car
from .models import Service


class ServiceForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(ServiceForm, self).__init__(*args, **kwargs)
        self.fields['car'] = forms.ModelChoiceField(
            queryset=Car.objects.filter(user=user, is_deleted=False),
            widget=forms.Select(attrs={'class': 'form-control'})
        )

    class Meta:
        model = Service
        fields = ['service_type', 'car', 'title', 'car_mileage', 'part_cost', 'cost_of_work',
                  'total_price', 'part_title', 'comment', 'photo']
        widgets = {
            'service_type': forms.Select(attrs={'class': 'form-control'}),
            'title': forms.TextInput(attrs={'class': 'form-control', 'maxlength': '100'}),
            'car_mileage': forms.NumberInput(attrs={'class': 'form-control', 'min': '1', 'max': '1000000'}),
            'cost_of_work': forms.NumberInput(attrs={'class': 'form-control', 'min': '1', 'max': '1000000'}),
            'part_cost': forms.NumberInput(attrs={'class': 'form-control', 'min': '1', 'max': '1000000'}),
            'total_price': forms.NumberInput(attrs={'class': 'form-control', 'min': '1', 'max': '1000000'}),
            'part_title': forms.TextInput(attrs={'class': 'form-control', 'maxlength': '100'}),
            'comment': forms.Textarea(attrs={'class': 'form-control', 'maxlength': '300'}),
            'photo': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

source/services/views.py
import json

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, UpdateView, CreateView
from garage.models import Car, CarMileageHistory
from .forms import ServiceForm
from .models import Service, ServiceType


class BaseView:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        service_types = ServiceType.objects.all()
        service_types_list = list(service_types.values('id', 'icon'))
        context['service_types'] = json.dumps(service_types_list)
        cars = Car.objects.filter(user=self.request.user)
        cars_list = []
        for car in cars:
            car_dict = {
                'id': car.id,
                'title': car.title,
                'state_number': car.state_number,
                'car_mileage': car.car_mileage,
            }
            if car.car_photo:
                car_dict['car_photo'] = self.request.build_absolute_uri(car.car_photo.url)
            cars_list.append(car_dict)
        context['cars'] = json.dumps(cars_list)
        return context


class ServiceBaseView(BaseView):
    pass


class ServicesListView(LoginRequiredMixin, ListView):
    model = Service
    template_name = 'services/service_list.html'
    context_object_name = 'services'
    paginate_by = 6
    paginate_orphans = 0

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cars'] = Car.objects.filter(user=self.request.user, is_deleted=False)
        return context

    def get_queryset(self):
        #  что пользователь видит только свои услуги
        car_id = self.request.GET.get('car_id')
        if car_id:
            return Service.objects.filter(car__user=self.request.user, is_deleted=False, car_id=car_id)
        else:
            return Service.objects.filter(car__user=self.request.user, is_deleted=False)


class ServiceDetailView(LoginRequiredMixin, DetailView):
    model = Service
    template_name = 'services/service_detail.html'
    context_object_name = 'service'

    def get_queryset(self):
        #  что пользователь видит только свои услуги
        return Service.objects.filter(car__user=self.request.user)


class ServiceUpdateView(LoginRequiredMixin, PermissionRequiredMixin, ServiceBaseView, UpdateView):
    model = Service
    form_class = ServiceForm
    template_name = 'services/service_update_form.html'
    permission_required = 'services.change_service'
    success_url = reverse_lazy('services_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user  # Передаем текущего пользователя в kwargs
        return kwargs

    def get_queryset(self):
        #  что пользователь редактирует только свои услуги
        return Service.objects.filter(car__user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_editing'] = True
        return context

    def form_valid(self, form):
        # Получаем экземпляр текущей услуги
        instance = form.save(commit=False)
        # Получаем экземпляр автомобиля, связанного с текущей услугой
        car = instance.car
        # Получаем все записи в истории пробега для данного автомобиля
        all_mileage_history = CarMileageHistory.objects.filter(car=car, is_deleted=False)
        # Получаем последнюю запись в истории пробега для данного автомобиля
        last_mileage_history = all_mileage_history.last()
        # Проверяем, является ли текущая услуга последней в истории пробега
        is_last_service = last_mileage_history and last_mileage_history.parent_object == instance
        # Если пробег был изменен и текущая услуга является последней в истории пробега
        if int(form.cleaned_data['car_mileage']) != car.car_mileage and is_last_service:
            # Обновляем пробег автомобиля на значение из формы
            car.car_mileage = form.cleaned_data['car_mileage']
            car.save()
        # Сохраняем изменения в текущей услуге
        instance.save()
        # Создаем новую запись в истории пробега после редактирования услуги
        CarMileageHistory.objects.create(
            car=car,
            car_mileage=form.cleaned_data['car_mileage'],
            content_type=ContentType.objects.get_for_model(Service),
            object_id=instance.id
        )

        return HttpResponseRedirect(self.get_success_url())


class ServiceCreateView(LoginRequiredMixin, PermissionRequiredMixin, ServiceBaseView, CreateView):
    model = Service
    form_class = ServiceForm
    template_name = 'services/service_update_form.html'
    permission_required = 'services.add_service'
    success_url = reverse_lazy('services_list')

    def get_form_kwargs(self):
        kwargs = super(ServiceCreateView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_editing'] = False
        return context

    def form_valid(self, form):
        response = super().form_valid(form)

        # Получаем экземпляр автомобиля, связанного с текущей услугой
        car = self.object.car

        # Обновляем пробег автомобиля на указанное значение в услуге
        car.car_mileage = form.cleaned_data['car_mileage']
        car.save()

        # Создаем запись в CarMileageHistory после создания услуги
        CarMileageHistory.objects.create(
            car=car,
            car_mileage=car.car_mileage,
            content_type=ContentType.objects.get_for_model(Service),
            object_id=self.object.id
        )

        return response


class ServiceDeleteView(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = 'services.delete_service'

    def get(self, request, *args, **kwargs):
        # Получаем объект удаляемой услуги
        service = get_object_or_404(Service, pk=kwargs['pk'], car__user=request.user)

        # Обновляем флаг is_deleted для услуги
        service.is_deleted = True
        service.save()

        # Находим связанные записи в CarMileageHistory и устанавливаем is_deleted = True
        CarMileageHistory.objects.filter(
            content_type=ContentType.objects.get_for_model(Service),
            object_id=service.id
        ).update(is_deleted=True)

        # Обновляем пробег у автомобиля
        car = service.car
        last_mileage_history = CarMileageHistory.objects.filter(
            car=car,
            is_deleted=False
        ).last()

        if last_mileage_history:
            car.car_mileage = last_mileage_history.car_mileage
            car.save()

        return redirect('services_list')

source/templates/services/service_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row">
    <div class="card col-md-6 " style="width: 18rem;">
        {% if service.photo %}
            <img src="{{ service.photo.url }}" class="card-img-top" alt="...">
                    {% else %}
                    <img src="{% static 'images/def_service_icon.png' %}" class="card-img-top" alt="...">
        {% endif %}
        <div class="card-body">
            <h5 class="card-title">{{ service.title }}</h5>

        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Car name: {{ service.car }}</li>
            <li class="list-group-item">Car mileage: {{ service.car_mileage }} km</li>
            <li class="list-group-item">Part Number №: {{ service.part_title }}</li>
            <li class="list-group-item">Part cost: {{ service.part_cost }}</li>
            <li class="list-group-item">Cost of work: {{ service.cost_of_work }}</li>
            <li class="list-group-item">Total price: {{ service.total_price }}</li>
        </ul>
        <div class="card-body">
            <a href="{% url 'service_update' service.id %}" class="btn btn-primary">Edit</a>
            <button type="button" class="btn btn-danger deleteButton" data-bs-toggle="modal" data-bs-target="#deleteModal" data-car-id="{{ service.id }}">
  Delete
</button>
        </div>
    </div>
<div class="col-md-1"></div>
<div class="card col-md-6" style="max-height: 200px; overflow-y: auto;">
            <div class="card-body">
            <h5 class="card-title">Comment</h5>
            <p class="card-text">{{ service.comment }}</p>
        </div>
</div>
</div>
    <!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Confirm deletion</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to remove this service?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <a href="" class="btn btn-primary" id="confirmDelete">Delete</a>

      </div>
    </div>
  </div>
</div>
     {% block js %}
    <!-- jQuery to handle the delete confirmation -->
<script>
$(document).ready(function(){
  $('.deleteButton').on('click', function(){
       console.log("Delete button clicked");

        var carId = $(this).data('car-id');
        var url = "/services/delete/" + carId;
        console.log("Delete URL: ", url);
        $('#confirmDelete').attr('href', url);
  });
});
</script>
    {% endblock %}

{% endblock %}

source/templates/services/service_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row mb-3">
<div class="col-md-2 mb-2"><a href="{% url 'service_create' %}" class="btn btn-primary">Add service</a></div>
            <div class="col-md-4">
            <form method="get" class="row">
                <div class="col-md-5 mb-2">
                    <select name="car_id" class="form-select" onchange="this.form.submit()">
                        <option value="">Choice Car</option>
                        {% for car in cars %}
                            <option value="{{ car.id }}"
                                    {% if car.id == selected_car_id %}selected{% endif %}>{{ car }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-md-3 mb-2">
                    <input class="btn btn-success" type="submit" value="Reset" onclick="this.form.car_id.value=''">
                </div>
            </form>
        </div>
    </div>
     {% include 'partials/pagination.html' %}
    <div class="row">
{% for service in object_list %}

    <div class="col-md-4">
    <div class="card md-3">

  <div class="card-header">

                     {% if service.service_type %}
            <img src="{{ service.service_type.icon.url }}" class="card-img-top" style="width: 30%" alt="...">
                    {% else %}
                    <img src="{% static 'images/def_service_icon.png' %}" class="card-img-top" style="width: 30%" alt="...">
        {% endif %}
   {{ service.title }}
  </div>

  <div class="card-body">
    <h5 class="card-title">Car name: {{ service.car }}</h5>
    <p class="card-text">{{ service.comment|slice:':30' }}</p>
    <p class="card-text">created_at - {{ service.created_at }}</p>
    <a href="{% url 'service_detail' service.id %}" class="btn btn-primary">More info</a>
  </div>
</div>
    </div>


{% endfor %}
    </div>
{% endblock %}

source/templates/services/service_update_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <h2>{% if is_editing %}Edit{% else %}Create{% endif %} service</h2>
  <form id="task-form" method="post" enctype="multipart/form-data" >
    {% csrf_token %}
   <div class="row">
       <div class="col-md-4">
            <div class="mb-3">
                {{ form.title.errors }}
                {{ form.title.label_tag }}
                {{ form.title }}
            </div>
            <div class="mb-3 row">
                <div class="col">
                {{ form.service_type.errors }}
                {{ form.service_type.label_tag }}
                {{ form.service_type }}</div>
                <div class="col-6">
                <img id="service-icon" src="{% static 'images/icon-car-engine.png' %}" alt="Service Icon" style="width: 35%"></div>
            </div>
            <div class="mb-3">
                {{ form.car.errors }}
                {{ form.car.label_tag }}
                {{ form.car }}
            </div>
           <div class="mb-3">
                {{ form.car_mileage.errors }}
                {{ form.car_mileage.label_tag }}
                {{ form.car_mileage }}
            </div>
            <div class="mb-3">
                {{ form.part_title.errors }}
                {{ form.part_title.label_tag }}
                {{ form.part_title }}
            </div>
               <div class="mb-3">
                {{ form.part_cost.errors }}
                {{ form.part_cost.label_tag }}
                {{ form.part_cost }}
            </div>
                          <div class="mb-3">
                {{ form.cost_of_work.errors }}
                {{ form.cost_of_work.label_tag }}
                {{ form.cost_of_work }}
            </div>
                           <div class="mb-3">
                {{ form.total_price.errors }}
                {{ form.total_price.label_tag }}
                {{ form.total_price }}
            </div>
       </div>
       <div class="col-md-3">
           <div class="col-md-4" id="car_card" style="display: none">
                <div class="card mb-2" style="width: 18rem;">
                        <img id="car_photo" src="{% static 'images/def_icon.png' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title" id="car_title"></h5>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item" >Number - <span id="car_state_number"></span></li>
                        <li class="list-group-item">Car mileage - <span id="car_car_mileage"></span></li>
                    </ul>
                </div>
            </div>
       </div>
       <div class="col-md-5">
            <div class="mb-3">
                {{ form.comment.errors }}
                {{ form.comment.label_tag }}
                {{ form.comment }}
            </div>
            <div class="mb-3" id="photo_file_card">
                {{ form.photo.errors }}
                {{ form.photo.label_tag }}
                {{ form.photo }}
            </div>
            <div class="col-md-4" id="service_photo_card" style="display: none">
                <div class="card mb-2" style="width: 18rem;">
                        <img id="service_photo_file" src="{% static 'images/def_icon.png' %}" class="card-img-top" alt="...">
                    
                </div>
            </div>
       </div>
   </div>

    <button type="submit" class="btn btn-primary">{% if is_editing %}Edit{% else %}Create{% endif %}</button>
      <a href="{% url 'services_list' %}" class="btn btn-danger">Cancel</a>
  </form>

{% endblock %}
{% block js %}
    <script >
        $(document).ready(function() {
    var serviceTypes = JSON.parse('{{ service_types|escapejs|safe }}');
    function updateIcon() {
        var selectedServiceType = $("#id_service_type").val();
        var serviceType = serviceTypes.find(function(serviceType) {
            return serviceType.id == selectedServiceType;
        });
        if (serviceType) {
            var iconUrl = '/uploads/' + serviceType.icon;  // Добавляем начальный путь /uploads/
            $('#service-icon').attr('src', iconUrl);
        }
    }

    $('#id_service_type').change(updateIcon);

    // Обновляем иконку при загрузке страницы
    updateIcon();
});
$(document).ready(function() {
    var cars = JSON.parse('{{ cars|escapejs|safe }}');
    function updateCarCard() {
        var selectedCar = $("#id_car").val();
        var car = cars.find(function(car) {
            return car.id == selectedCar;
        });
        if (car) {
            $('#car_card').show();
            $('#car_photo').attr('src', car.car_photo);
            $('#car_title').text(car.title);
            $('#car_state_number').text(car.state_number);
            $('#car_car_mileage').text(car.car_mileage);
        } else {
            $('#car_card').hide();
        }
    }

    $('#id_car').change(updateCarCard);

    // Обновляем карточку автомобиля при загрузке страницы
    updateCarCard();
});
$(document).ready(function() {
    // Функция для обновления общей стоимости
    function updateTotalPrice() {
        var partCost = parseFloat($('#id_part_cost').val()) || 0;  // Получаем стоимость детали или 0, если поле пустое
        var costOfWork = parseFloat($('#id_cost_of_work').val()) || 0;  // Получаем стоимость работы или 0, если поле пустое
        var totalPrice = partCost + costOfWork;  // Суммируем стоимость детали и работы
        $('#id_total_price').val(totalPrice.toFixed(2));  // Обновляем общую стоимость с округлением до 2 знаков после запятой
    }

    // Добавляем обработчики событий для полей стоимости детали и работы
    $('#id_part_cost, #id_cost_of_work').change(updateTotalPrice);

    // Обновляем общую стоимость при загрузке страницы
    updateTotalPrice();
});
$(document).ready(function() {
    // Получаем URL текущего изображения
    var currentImageUrl = $('#photo_file_card a').attr('href');
    if (currentImageUrl) {
        // Если URL существует
        // Отображаем карточку с изображением и устанавливаем URL изображения
        $('#service_photo_card').show();
        $('#service_photo_file').attr('src', currentImageUrl);
    }
});

$(document).ready(function() {
    // Функция для чтения и отображения выбранного изображения
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function(e) {
                $('#service_photo_file').attr('src', e.target.result);
                $('#service_photo_card').show();  // Показываем карточку с изображением
            }
            reader.readAsDataURL(input.files[0]);
        }
    }

    // Добавляем обработчик событий для поля загрузки файла
    $('#id_photo').change(function() {
        readURL(this);
    });
});

$(document).ready(function() {
    // Функция для проверки значения пробега
    function checkMileage() {
        var carMileage = parseInt($('#id_car_mileage').val());
        var carCarMileage = parseInt($('#car_car_mileage').text());

        if (carMileage < carCarMileage) {
            alert('The mileage cannot be less than the current mileage of the car!');
            $('#id_car_mileage').val(carCarMileage);
        }
    }

    // Проверяем значение пробега, когда поле теряет фокус, только если текст кнопки отправки формы равен "Create"
    $('#id_car_mileage').on('blur', function() {
        if ($('button[type="submit"]').text() === "Create") {
            checkMileage();
        }
    });
});
</script>
    {% endblock %}