source/fuel/urls.py
from django.urls import path
from .views import FuelListView, FuelCreateView, FuelUpdateView, FuelDeleteView
urlpatterns = [
    path('list/', FuelListView.as_view(), name='fuel_list'),
    # path('detail/<int:pk>', ServiceDetailView.as_view(), name='service_detail'),
    path('update/<int:pk>', FuelUpdateView.as_view(), name='fuel_update'),
    path('create/', FuelCreateView.as_view(), name='fuel_create'),
    path('delete/<int:pk>', FuelDeleteView.as_view(), name='fuel_delete'),

]

source/source/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from source.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home_page'),
    path('accounts/', include('accounts.urls')),
    path('garage/', include('garage.urls')),
    path('services/', include('services.urls')),
    path('notifications/', include('notifications.urls')),
    path('fuels/', include('fuel.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/fuel/models.py
from django.db import models
from django.contrib.auth import get_user_model

from garage.models import Car


class FuelType(models.Model):
    FUEL_TYPES = (
        ('92', '92'),
        ('95', '95'),
        ('98', '98'),
        ('Diesel', 'Diesel'),
    )
    fuel_type = models.CharField(max_length=50, choices=FUEL_TYPES)
    fuel_photo = models.ImageField(upload_to='fuels/', verbose_name='fuel_photo', null=True, blank=True)

    def __str__(self):
        return self.fuel_type


class Fuel(models.Model):
    fuel_type = models.ForeignKey(FuelType, on_delete=models.SET_NULL, null=True, blank=True)
    price_per_liter = models.DecimalField(max_digits=5, decimal_places=2)
    fuel_volume = models.DecimalField(max_digits=5, decimal_places=2)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    car_mileage = models.IntegerField(null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    edited_at = models.DateTimeField(auto_now=True)

    is_deleted = models.BooleanField(default=False)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.PROTECT)

    def __str__(self):
        return f'{self.fuel_type} - {self.car}'

source/fuel/forms.py
from django import forms
from garage.models import Car
from .models import Fuel


class FuelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(FuelForm, self).__init__(*args, **kwargs)
        self.fields['car'] = forms.ModelChoiceField(
            queryset=Car.objects.filter(user=user, is_deleted=False),
            widget=forms.Select(attrs={'class': 'form-control'})
        )

    class Meta:
        model = Fuel
        fields = ['fuel_type', 'car', 'price_per_liter', 'fuel_volume', 'total_amount', 'car_mileage']
        widgets = {
            'fuel_type': forms.Select(attrs={'class': 'form-control'}),
            'price_per_liter': forms.NumberInput(attrs={'class': 'form-control', 'min': '1', 'max': '1000000'}),
            'fuel_volume': forms.NumberInput(attrs={'class': 'form-control', 'min': '1', 'max': '1000000'}),
            'total_amount': forms.NumberInput(attrs={'class': 'form-control', 'min': '1', 'max': '1000000'}),
            'car_mileage': forms.NumberInput(attrs={'class': 'form-control', 'min': '1', 'max': '1000000'}),

        }

source/fuel/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, CreateView, UpdateView
from django.contrib.contenttypes.models import ContentType
from garage.models import CarMileageHistory
from .models import Fuel, Car
from .forms import FuelForm
import json


class BaseView:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cars = Car.objects.filter(user=self.request.user)
        cars_list = []
        for car in cars:
            car_dict = {
                'id': car.id,
                'title': car.title,
                'state_number': car.state_number,
                'car_mileage': car.car_mileage,
            }
            if car.car_photo:
                car_dict['car_photo'] = self.request.build_absolute_uri(car.car_photo.url)
            cars_list.append(car_dict)
        context['cars'] = json.dumps(cars_list)
        return context


class FuelBaseView(BaseView):
    pass


class FuelListView(LoginRequiredMixin, ListView):
    model = Fuel
    template_name = 'fuel/fuel_list.html'
    context_object_name = 'fuels'
    paginate_by = 6
    paginate_orphans = 0

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cars'] = Car.objects.filter(user=self.request.user, is_deleted=False)
        return context

    def get_queryset(self):
        car_id = self.request.GET.get('car_id')
        if car_id:
            fuels = Fuel.objects.filter(car__user=self.request.user, car_id=car_id)
        else:
            fuels = Fuel.objects.filter(car__user=self.request.user)

        for fuel in fuels:
            # Получаем предыдущую запись Fuel для данного автомобиля, которая не была удалена
            previous_fuel = Fuel.objects.filter(car=fuel.car, created_at__lt=fuel.created_at,
                                                is_deleted=False).order_by('-created_at').first()

            # Если есть предыдущая запись Fuel
            if previous_fuel:
                # Вычисляем разницу в пробеге
                mileage_difference = fuel.car_mileage - previous_fuel.car_mileage

                # Вычисляем средний расход топлива на 100 км и округляем до двух десятичных знаков
                fuel.average_fuel_consumption = round((fuel.fuel_volume / mileage_difference * 100),
                                                      2) if mileage_difference else 0
            else:
                fuel.average_fuel_consumption = 0

        return fuels


class FuelCreateView(LoginRequiredMixin, PermissionRequiredMixin, FuelBaseView, CreateView):
    model = Fuel
    form_class = FuelForm
    template_name = 'fuel/fuel_update_form.html'
    permission_required = 'fuel.add_fuel'
    success_url = reverse_lazy('fuel_list')

    def get_form_kwargs(self):
        kwargs = super(FuelCreateView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_editing'] = False
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()

        # Получаем экземпляр автомобиля, связанного с текущим заправкой
        car = self.object.car

        # Обновляем пробег автомобиля на указанное значение в заправке
        car.car_mileage = form.cleaned_data['car_mileage']
        car.save()

        # Создаем запись в CarMileageHistory после создания заправки
        CarMileageHistory.objects.create(
            car=car,
            car_mileage=car.car_mileage,
            content_type=ContentType.objects.get_for_model(Fuel),
            object_id=self.object.id
        )

        return super().form_valid(form)


class FuelUpdateView(LoginRequiredMixin, PermissionRequiredMixin, FuelBaseView, UpdateView):
    model = Fuel
    form_class = FuelForm
    template_name = 'fuel/fuel_update_form.html'
    permission_required = 'fuel.change_fuel'
    success_url = reverse_lazy('fuel_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user  # Передаем текущего пользователя в kwargs
        return kwargs

    def get_queryset(self):
        #  что пользователь редактирует только свои заправки
        return Fuel.objects.filter(car__user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_editing'] = True
        return context

    def form_valid(self, form):
        # Получаем экземпляр текущей заправки
        instance = form.save(commit=False)
        # Получаем экземпляр автомобиля, связанного с текущей заправкой
        car = instance.car
        # Получаем все записи в истории пробега для данного автомобиля
        all_mileage_history = CarMileageHistory.objects.filter(car=car, is_deleted=False)
        # Получаем последнюю запись в истории пробега для данного автомобиля
        last_mileage_history = all_mileage_history.last()
        # Проверяем, является ли текущая заправка последней в истории пробега
        is_last_fuel = last_mileage_history and last_mileage_history.parent_object == instance
        # Если пробег был изменен и текущая заправка является последней в истории пробега
        if int(form.cleaned_data['car_mileage']) != car.car_mileage and is_last_fuel:
            # Обновляем пробег автомобиля на значение из формы
            car.car_mileage = form.cleaned_data['car_mileage']
            car.save()
        # Сохраняем изменения в текущей заправке
        instance.save()
        # Создаем новую запись в истории пробега после редактирования заправки
        CarMileageHistory.objects.create(
            car=car,
            car_mileage=form.cleaned_data['car_mileage'],
            content_type=ContentType.objects.get_for_model(Fuel),
            object_id=instance.id
        )

        return HttpResponseRedirect(self.get_success_url())


class FuelDeleteView(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = 'fuel.delete_fuel'

    def get(self, request, *args, **kwargs):
        # Получаем объект удаляемой заправки
        fuel = get_object_or_404(Fuel, pk=kwargs['pk'], car__user=request.user)

        # Обновляем флаг is_deleted для заправки
        fuel.is_deleted = True
        fuel.save()

        # Находим связанные записи в CarMileageHistory и устанавливаем is_deleted = True
        CarMileageHistory.objects.filter(
            content_type=ContentType.objects.get_for_model(Fuel),
            object_id=fuel.id
        ).update(is_deleted=True)

        # Обновляем пробег у автомобиля
        car = fuel.car
        last_mileage_history = CarMileageHistory.objects.filter(
            car=car,
            is_deleted=False
        ).last()

        if last_mileage_history:
            car.car_mileage = last_mileage_history.car_mileage
            car.save()

        return redirect('fuel_list')

source/templates/fuel/fuel_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="row mb-3">
        <div class="col-md-2 mb-2"><a href="{% url 'fuel_create' %}" class="btn btn-primary">Add </a></div>
        <div class="col-md-4">
            <form method="get" class="row">
                <div class="col-md-5 mb-2">
                    <select name="car_id" class="form-select" onchange="this.form.submit()">
                        <option value="">Choice Car</option>
                        {% for car in cars %}
                            <option value="{{ car.id }}"
                                    {% if car.id == selected_car_id %}selected{% endif %}>{{ car }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-md-3 mb-2">
                    <input class="btn btn-success" type="submit" value="Reset" onclick="this.form.car_id.value=''">
                </div>
            </form>
        </div>
    </div>
    {% include 'partials/pagination.html' %}
    <div class="container">
        <h2>Car Fuel History</h2>

        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">Car name</th>
                <th scope="col">Icon</th>
                <th scope="col">Fuel type</th>
                <th scope="col">Price per liter</th>
                <th scope="col">Fuel volume</th>
                <th scope="col">Total amount</th>
                <th scope="col">Car mileage</th>
                <th scope="col">AVG-100km</th>
                <th scope="col">Created at</th>
                <th scope="col">Is deleted</th>
                <th scope="col">btn</th>
            </tr>
            </thead>
            <tbody>
            {% for fuel in fuels %}
                <tr>
                    <td>{{ fuel.car }}</td>
                    <td style="width: 5%"><img src="{{ fuel.fuel_type.fuel_photo.url }}" style="width: 80%" alt=""></td>
                    <td>{{ fuel.fuel_type }}</td>
                    <td >{{ fuel.price_per_liter }}</td>
                    <td >{{ fuel.fuel_volume }} L</td>
                    <td >{{ fuel.total_amount }}</td>
                    <td>{{ fuel.car_mileage }} Km</td>
                <td>{{ fuel.average_fuel_consumption }} L</td>
                    <td>{{ fuel.created_at }}</td>
                    <td>{% if fuel.is_deleted %}Yes{% else %}No{% endif %}</td>
                    {% if not fuel.is_deleted %}
                        <td><a href="{% url 'fuel_update' fuel.id %}" class="btn btn-primary">Edit</a>
                            <button type="button" class="btn btn-danger deleteButton" data-bs-toggle="modal"
                                    data-bs-target="#deleteModal" data-car-id="{{ fuel.id }}">
                                Delete
                            </button>
                        </td>
                    {% else %}
                        <td><a href="#" class="btn btn-primary disabled">Edit</a>
                            <button type="button" class="btn btn-danger disabled deleteButton" data-bs-toggle="modal"
                                    data-bs-target="#deleteModal" data-car-id="#">
                                Delete
                            </button>
                        </td>
                    {% endif %}
                </tr>
            {% empty %}
                <tr>
                    <td colspan="3">No records found.</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>




    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Confirm deletion</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Are you sure you want to remove this service?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <a href="" class="btn btn-primary" id="confirmDelete">Delete</a>

                </div>
            </div>
        </div>
    </div>
    {% block js %}
        <!-- jQuery to handle the delete confirmation -->
        <script>
            $(document).ready(function () {
                $('.deleteButton').on('click', function () {
                    console.log("Delete button clicked");

                    var carId = $(this).data('car-id');
                    var url = "/fuels/delete/" + carId;
                    console.log("Delete URL: ", url);
                    $('#confirmDelete').attr('href', url);
                });
            });
            $(document).ready(function () {
                // Функция для расчета итоговой суммы
                function calculateTotal() {
                    var pricePerLiter = parseFloat($('#price_liter').text());
                    var fuelVolume = parseFloat($('#fuel_vol').text());
                    console.log('123')
                    if (!isNaN(pricePerLiter) && !isNaN(fuelVolume)) {
                        var totalAmount = pricePerLiter * fuelVolume;
                        $('#total_sum').text(totalAmount.toFixed(2));
                    }
                }

                // Вызываем функцию при загрузке страницы
                calculateTotal();

                // Вызываем функцию при изменении значений
                $('#price_liter, #fuel_vol').on('input', calculateTotal);
            });
        </script>
    {% endblock %}




{% endblock %}

source/templates/fuel/fuel_update_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <h2>{% if is_editing %}Edit{% else %}Create{% endif %} Fuel Entry</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-3">
                <div class="mb-3">
                    {{ form.fuel_type.errors }}
                    {{ form.fuel_type.label_tag }}
                    {{ form.fuel_type }}
                </div>
                <div class="mb-3">
                    {{ form.car.errors }}
                    {{ form.car.label_tag }}
                    {{ form.car }}
                </div>
                <div class="mb-3" id="price_liter">
                    {{ form.price_per_liter.errors }}
                    {{ form.price_per_liter.label_tag }}
                    {{ form.price_per_liter }}
                </div>
                <div class="mb-3" id="fuel_vol">
                    {{ form.fuel_volume.errors }}
                    {{ form.fuel_volume.label_tag }}
                    {{ form.fuel_volume }}
                </div>
                <div class="mb-3" id="total_sum">
                    {{ form.total_amount.errors }}
                    {{ form.total_amount.label_tag }}
                    {{ form.total_amount }}
                </div>
                <div class="mb-3">
                    {{ form.car_mileage.errors }}
                    {{ form.car_mileage.label_tag }}
                    {{ form.car_mileage }}
                </div>
</div>
                          <div class="col-md-3">
             <div class="col-md-4" id="car_card" style="display: none">
                <div class="card mb-2" style="width: 18rem;">
                        <img id="car_photo" src="{% static 'images/def_icon.png' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title" id="car_title"></h5>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item" >Number - <span id="car_state_number"></span></li>
                        <li class="list-group-item">Car mileage - <span id="car_car_mileage"></span></li>
                    </ul>
                </div>
            </div>
          </div>
            </div>
                <button type="submit" class="btn btn-primary">{% if is_editing %}Edit{% else %}Create{% endif %}</button>
      <a href="{% url 'fuel_list' %}" class="btn btn-danger">Cancel</a>
        </form>
    </div>

    {% block js %}
        <!-- jQuery to handle the delete confirmation -->
        <script>
$(document).ready(function () {
    // Функция для расчета итоговой суммы
    function calculateTotal() {
        var pricePerLiter = parseFloat($('#id_price_per_liter').val());
        var fuelVolume = parseFloat($('#id_fuel_volume').val());

        if (!isNaN(pricePerLiter) && !isNaN(fuelVolume)) {
            var totalAmount = pricePerLiter * fuelVolume;
            $('#id_total_amount').val(totalAmount.toFixed(2));
        }
    }

    // Вызываем функцию при изменении значений
    $('#id_price_per_liter, #id_fuel_volume').on('input', calculateTotal);
});
$(document).ready(function() {
    var cars = JSON.parse('{{ cars|escapejs|safe }}');
    function updateCarCard() {
        var selectedCar = $("#id_car").val();
        var car = cars.find(function(car) {
            return car.id == selectedCar;
        });
        if (car) {
            $('#car_card').show();
            $('#car_photo').attr('src', car.car_photo);
            $('#car_title').text(car.title);
            $('#car_state_number').text(car.state_number);
            $('#car_car_mileage').text(car.car_mileage);
        } else {
            $('#car_card').hide();
        }
    }

    $('#id_car').change(updateCarCard);

    // Обновляем карточку автомобиля при загрузке страницы
    updateCarCard();
});
$(document).ready(function() {
    // Функция для проверки значения пробега
    function checkMileage() {
        var carMileage = parseInt($('#id_car_mileage').val());
        var carCarMileage = parseInt($('#car_car_mileage').text());

        if (carMileage < carCarMileage) {
            alert('The mileage cannot be less than the current mileage of the car!');
            $('#id_car_mileage').val(carCarMileage);
        }
    }

    // Проверяем значение пробега, когда поле теряет фокус, только если текст кнопки отправки формы равен "Create"
    $('#id_car_mileage').on('blur', function() {
        if ($('button[type="submit"]').text() === "Create") {
            checkMileage();
        }
    });
});
        </script>
    {% endblock %}
{% endblock %}